"TELEGRAM_BOT_TOKEN": "<YOUR TELEGRAM BOT TOKEN>"
"TELEGRAM_CHAT_IDS": {"<PERSON1>":"<CHAT_ID1>", "<PERSON2>":"<CHAT_ID2>"}
"MY_GARMIN_PASSWORD": "<YOUR_GARMIN_PASSWORD>" 
"MY_EMAIL_ADDRESS": "<YOUR_GARMIN_USERNAME/EMAIL_ADDRESS>>"